### PR TITLE
fix: address the v2 api endpoint

### PR DESCRIPTION
**Pull request by svietry**
https://anchore.atlassian.net/browse/ENTERPRISE-2926

### CODE REVIEW

**Review by robcresswell — CHANGES_REQUESTED** [review]
This might not be needed, it looks like `v1.0.3` was tagged incorrectly, perhaps thats causing the issue? It points to an older version (same as `v1.0.2`) before https://github.com/anchore/k8s-inventory/commit/ebbacb49fbf1d79ca84af7a8b141e50f16c1a89f was merged

**Comment by robcresswell** [comment]
Been discussing this with Brad, I think we've settled on

- Default to v2
- Run a check on init, as well as on failure
- Make the failure check specific to 404

**Comment by bradleyjones** [comment]
Just an update on ^^, rather than running a check specifically on init I just changed the logic so that it will do a retry immediately on failure so basically the first post will sort the version out and retry again so no need to collect the inventory again. Should just keep all this logic contained to the reporter package rather than having to pull it out calls to check the version on init.

**Review by svietry — COMMENTED** [review]
Looks good

**Review by robcresswell — COMMENTED** [review]
I think the implementation is fine, but I'd like if we could squash the commit history and add a useful commit message. Something that explains the constraints (< 4.9 is v1 only, >= 4.9, < 5.0 is v1 & v2, >= 5.0 is v2) as well as the reasoning for the solution; default to v2, on a 404 make a reasonable assumption that v1 exists and is safe to use.

Also I think in theory there could be a problem if the customer somehow gets a 404 that isn't a version problem. I think the code would just hammer the API checking versions as fast as Go could manage, which I'd guess is quite fast. I'm not sure this would ever occur in practice, though.

**Review by robcresswell — APPROVED** [review]

**Comment by bradleyjones** [comment]
> Also I think in theory there could be a problem if the customer somehow gets a 404 that isn't a version problem. I think the code would just hammer the API checking versions as fast as Go could manage, which I'd guess is quite fast. I'm not sure this would ever occur in practice, though.

If the checkVersion get's a 404 then we return an error and don't retry, so it only retries if the post 404s and the check version returns a 200 and the endpoint is different. We should be ok here because if the version response fails then we don't retry

**Pull request merged**
